---
- name: task1_1
  hosts: node1.example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root

  tasks:
  - name: install httpd
    package: name=httpd

  - name: enabling httpd service
    service: name=httpd enabled=yes

  - name: status httpd started
    service: name=httpd state=started

  - name: creating html-file
    copy:
     content: "Welcome to my webserver!"
     dest: /var/www/html/index.html
     owner: ansible
     group: ansible
     mode: 0644

  - name: Enabling 80 (http)
    firewalld:
     service: http
     state: enabled
     permanent: yes
     immediate: yes

  - name: Enabling 443 (https)
    firewalld:
     service: https
     state: enabled
     permanent: yes
     immediate: yes

...

