---
- name: task1_2
  hosts: node1.example.com
  user: ansible
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: uninstall httpd
    yum:
     name: httpd
     autoremove: yes
     state: absent

  - name: deleting html-file
    file:
     path: '/var/www/html/index.html'
     state: absent

  - name: Disabling 80 (http)
    firewalld:
     service: http
     state: disabled
     permanent: yes
     immediate: yes

  - name: Disabling 443 (https)
    firewalld:
     service: https
     state: disabled
     permanent: yes
     immediate: yes

...

